name: wiki
on:
  push:
    branches:
      - master
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # 创建并切换到 'wiki' 分支
      - name: Create and switch to 'wiki' branch
        run: |
          git checkout -b wiki  # 创建并切换到 'wiki' 分支
          git push -u origin wiki  # 将 'wiki' 分支推送到远程仓库

      - uses: actions/setup-python@v2  # 更新为使用 v2 版本的 Python
        with:
          python-version: 3.x

      # 进入到 'wiki' 目录，安装依赖并部署
      - name: Install dependencies and deploy
        run: |
          cd wiki  # 进入到 'wiki' 目录
          pip install mkdocs mkdocs-material pymdown-extensions mkdocs-dracula-theme  # 安装所需的依赖
          mkdocs gh-deploy --force  # 在 'wiki' 目录下执行部署命令
