name: wiki
on:
  push:
    branches:
      - master
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
          architecture: "x64"
          token: ${{ secrets.GITHUB_TOKEN }}
          cache-dependency-path: .cache

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          architecture: "x64"
          token: ${{ secrets.GITHUB_TOKEN }}
          cache: "npm"

      - name: Install dependencies and deploy
        run: |
          cd wiki  # 进入到 'wiki' 目录
          pip install mkdocs mkdocs-material pymdown-extensions mkdocs-dracula-theme  # 安装所需的依赖
          mkdocs gh-deploy --force  # 在 'wiki' 目录下执行部署命令
