name: wiki
on:
  push:
    branches:
      - master
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Switch branch to 'wiki'
        run: git checkout -b wiki
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material
      - run: pip install pymdown-extensions
      - name: Change directory to 'wiki' and deploy
        run: |
          cd wiki  # 进入到 'wiki' 目录
          mkdocs gh-deploy --force  # 在 'wiki' 目录下执行部署命令
